# Generated by Django 4.1.2 on 2022-10-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp02", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="board_idx", new_name="board",
        ),
    ]
