# Generated by Django 4.1.2 on 2022-10-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=600)),
                ("content", models.TextField(null=True)),
                ("point", models.IntegerField(default=0)),
            ],
        ),
    ]
